### ISSUE TITLE
维度分析的时候，拖动维度界面报空指针异常。

### ISSUE THREAD

**Issue by liujiliang2008** [ruisibi/rsbi-os#3]
![image](https://user-images.githubusercontent.com/4192239/108824628-e76fbc00-75fc-11eb-81c4-64a9b43451d2.png)

但是sql能在数据库里查到数据

![image](https://user-images.githubusercontent.com/4192239/108824698-fe161300-75fc-11eb-8784-a04411bb1b1b.png)

这个对象经过一波针对null的处理逻辑后，还是null

![image](https://user-images.githubusercontent.com/4192239/108824766-11c17980-75fd-11eb-8865-1fc9abc73c2a.png)

**Comment by ruisibi** [comment]
已解决， [https://github.com/ruisibi/rsbi-os/commit/66658d8842ee89af9726571f1dc3d4aee6793248](url)
